spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "QA Environment"
  contactDetails:
    name: "QA"
    email: "qa@cards.com"
  onCallSupport:
    - (000)000-1234
    - (000)000-5678